### ISSUE TITLE
第五章“5.2条件测试：相等”及“5.2条件测试：不等”中的问题

### ISSUE THREAD

**Issue by lilacvapor** [scruel/pcc_3e_slides#1]
您好，请问这两页的运行结果是不是写反了？
![image](https://github.com/scruel/pcc_3e_slides/assets/17161391/7343ecb4-b4f7-4a16-9c27-bb377fc367b9)
![image](https://github.com/scruel/pcc_3e_slides/assets/17161391/a5933886-08c3-4cdc-aadc-887217efb46c)

**Comment by scruel** [comment]
🤣确实，感谢指正，我来改一下，谢谢
