### ISSUE TITLE
第9章p48代码是不是错了？

### ISSUE THREAD

**Issue by meichiny** [scruel/pcc_3e_slides#12]
这个运行显示错误，super 没有 attribute

`def get_descriptive_name(self):
    return f"super.get_descriptive_name()} {self.battery_size}".title()`

![image](https://github.com/user-attachments/assets/fbdd4ffd-0d20-46ad-acc7-5ae655c0b602)

**Comment by scruel** [comment]
没错的，由于版面限制，部分代码是省略的，需要一页一页看着写，我抽空把每页的完整代码也放进仓库吧
